---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "gamekube.server.name" . }}
  labels:
    {{- include "gamekube.server.labels" . | nindent 4 }}
spec:
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8080
  selector:
    {{- include "gamekube.server.selectorLabels" . | nindent 4 }}
